name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CRS-JEDI-G4-Flipkart-POS

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      DB_DATABASE: crs
      DB_USER: root
      DB_PASSWORD: root
    defaults:
      run:
        working-directory: ./CRS-JEDI-G4-Flipkart-POS
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Run with gradle
        run: ./gradlew run << 3

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"