name: Java CI

on: [push, pullrequest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: cd
        run: cd CRS-JEDI-G4-Flipkart-POS
      - name: Build with Gradle
        run: ./gradlew build
