name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CRS-JEDI-G4-Flipkart-POS

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: crs
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    defaults:
      run:
        working-directory: ./CRS-JEDI-G4-Flipkart-POS
    steps:
      - name: Run with gradle
        run: ./gradlew run << 3

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"